export const GET_CART_COUNT = "GET_CART_COUNT";
export const SET_CART_COUNT = "SET_CART_COUNT";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const SET_CART_ITEMS = "SET_CART_ITEMS";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"