export const GET_COMBINED_PRODUCT_DETAILS = 'GET_COMBINED_PRODUCT_DETAILS';
export const SET_COMBINED_PRODUCT_DETAILS = 'SET_COMBINED_PRODUCT_DETAILS';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const SET_PRODUCT_BY_ID = 'SET_PRODUCT_BY_ID';