export const GET_COMBINED_CATALOG = "GET_COMBINED_CATALOG"
export const SET_COMBINED_CATALOG = "SET_COMBINED_CATALOG"

export const GET_CATALOG = "GET_CATALOG"
export const SET_CATALOG = "SET_CATALOG"

export const GET_PRODUCTS_BY_CATALOG_ID = "GET_PRODUCTS_BY_CATALOG_ID"
